# Generated by Django 4.1.7 on 2023-03-09 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primu', '0002_car_hp_car_yearofregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rimBrand', models.CharField(max_length=30)),
                ('rimModel', models.CharField(max_length=30)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('carModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primu.car')),
            ],
        ),
        migrations.CreateModel(
            name='RaceTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lenght', models.IntegerField(default=0)),
                ('style', models.CharField(max_length=30)),
                ('surface', models.CharField(max_length=30)),
                ('recordHolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primu.car')),
            ],
        ),
    ]
