# Generated by Django 4.1.7 on 2023-03-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('mod', models.CharField(max_length=35)),
                ('chasisNr', models.CharField(max_length=20)),
            ],
        ),
    ]
