# Generated by Django 4.1.7 on 2023-03-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primu', '0003_rims_racetracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addres', models.CharField(max_length=40)),
                ('cnp', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='rims',
            name='carModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rims', to='primu.car'),
        ),
        migrations.CreateModel(
            name='OwnersCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('kmWhenBought', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primu.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primu.owners')),
            ],
        ),
    ]
